spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: false
  liquibase:
    enabled: false
  security:
    user:
      name: testuser
      password: testpass

jwt:
  secret: test-jwt-secret-key-very-long-for-testing-1234567890
  expiration: 3600000

app:
  encryption:
    key: test-encryption-key-32-chars-long-1234567890

logging:
  config: classpath:logback-spring.xml
  level:
    root: WARN
    com.bank: DEBUG
    org.springframework.security: WARN

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: false
